(()=>{'use strict';
const K='miaomiao-study-desk-v2',$=s=>document.querySelector(s),nav=$('#nav'),page=$('#page');
const navs=[['home','首页','⌂'],['chinese','语文','📖'],['math','数学','123'],['english','英语','ABC'],['sport','运动','🪢'],['shop','商城','🛒'],['pet','宠物','🐱'],['rewards','奖励','🎁'],['calendar','日历','🗓️']];
const meta={chinese:['语文','📖','#f6e4e8'],math:['数学','123','#eaf2fb'],english:['英语','ABC','#f9efde'],sport:['运动','🪢','#e7f4ea']};
const wd=['日','一','二','三','四','五','六'];
const defaults=[
{id:'cn-write',subject:'chinese',name:'练字',icon:'✍️',days:[0,1,2,3,4,5,6],core:1,builtin:1},
{id:'cn-read',subject:'chinese',name:'阅读',icon:'📖',days:[0,1,2,3,4,5,6],core:1,builtin:1},
{id:'math-homework',subject:'math',name:'数学作业',icon:'➕',days:[0,1,2,3,4,5,6],core:1,builtin:1},
{id:'en-listen',subject:'english',name:'英语听力',icon:'🎧',days:[0,1,2,3,4,5,6],core:1,builtin:1},
{id:'en-raz',subject:'english',name:'RAZ',icon:'🔤',days:[0,1,2,3,4,5,6],core:1,builtin:1},
{id:'sp-rope',subject:'sport',name:'跳绳',icon:'🪢',days:[1,2,3,4],core:1,builtin:1},
{id:'sp-badminton',subject:'sport',name:'羽毛球',icon:'🏸',days:[0,5],core:1,builtin:1},
{id:'sp-free',subject:'sport',name:'自由运动',icon:'🌿',days:[6],core:1,builtin:1}
];
const fixedRewards=[{id:'tv',title:'看电视半小时',emoji:'📺',points:36,days:3},{id:'snack',title:'小零食',emoji:'🍪',points:60,days:5},{id:'toy',title:'小玩具',emoji:'🎁',points:84,days:7}];
const shop=[
['food-kibble','食物','猫粮','🥣',8,'feed'],['food-treat','食物','猫条','🐟',5,'feed'],['food-can','食物','主食罐头','🥫',10,'feed'],['food-freeze','食物','冻干','🍗',7,'feed'],
['toy-wand','玩具','逗猫棒','🪶',8,'play'],['toy-ball','玩具','小球','⚽',6,'play'],['toy-scratch','玩具','猫抓板','🧶',12,'play'],['toy-box','玩具','纸箱','📦',4,'play'],
['care-brush','洗漱','梳毛刷','🪮',6,'groom'],['care-bath','洗漱','洗护套装','🫧',12,'bath'],['care-towel','洗漱','小毛巾','🧺',5,'groom'],['care-nail','洗漱','指甲护理','✨',8,'groom'],
['med-kit','医疗','护理包','🧰',10,'treat'],['med-cone','医疗','护理头套','🔶',9,'treat'],['med-check','医疗','体检券','🩺',14,'treat'],['med-rest','医疗','休息垫','🛏️',7,'rest']
].map(x=>({id:x[0],cat:x[1],name:x[2],emoji:x[3],cost:x[4],action:x[5]}));
const init=()=>({points:0,fish:0,tasks:structuredClone(defaults),records:{},inventory:{},pet:{mood:82,message:'等你完成任务，我们一起玩吧！'},customRewards:[],rewardLog:[],shopCat:'食物'});
let state=(()=>{try{return {...init(),...JSON.parse(localStorage.getItem(K)||'{}')}}catch{return init()}})(),cur='home',tp=0,timer=null,pauseUntil=0;
const save=()=>localStorage.setItem(K,JSON.stringify(state));
const key=(d=new Date())=>d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');
const tasks=d=>state.tasks.filter(t=>t.days.includes(d.getDay())),core=d=>tasks(d).filter(t=>t.core),done=(id,k=key())=>(state.records[k]?.completed||[]).includes(id);
const rec=k=>state.records[k]||(state.records[k]={completed:[]});
const full=d=>{const c=core(d);return c.length&&c.every(t=>(state.records[key(d)]?.completed||[]).includes(t.id))};
const weekStart=(d=new Date())=>{let x=new Date(d),n=(x.getDay()+6)%7;x.setDate(x.getDate()-n);x.setHours(0,0,0,0);return x};
const weekDates=()=>{const s=weekStart();return Array.from({length:7},(_,i)=>{let d=new Date(s);d.setDate(s.getDate()+i);return d})};
const weekFull=()=>{let n=new Date();n.setHours(23,59,59,999);return weekDates().filter(d=>d<=n&&full(d)).length};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function toast(m){const t=$('#toast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function renderNav(){nav.innerHTML=navs.map(([id,l,i])=>`<button class="nav-btn ${cur===id?'active':''}" data-p="${id}"><i>${i}</i>${l}</button>`).join('');nav.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>go(b.dataset.p))}
function go(p){cur=p;clearInterval(timer);renderNav();render()}
function render(){({home,renderSubjectChinese:()=>subject('chinese'),renderSubjectMath:()=>subject('math'),renderSubjectEnglish:()=>subject('english'),renderSubjectSport:()=>subject('sport'),shop:renderShop,pet:renderPet,rewards:renderRewards,calendar:renderCalendar}[cur]||home)()}
function home(){
const d=new Date(),tt=tasks(d),cc=core(d),n=cc.filter(t=>done(t.id)).length,p=cc.length?Math.round(n/cc.length*100):0,pages=Math.max(1,Math.ceil(tt.length/3));tp=Math.min(tp,pages-1);const slice=tt.slice(tp*3,tp*3+3);
page.innerHTML=`<div class="home-grid">
<article class="card soft-pink"><div class="card-head"><div class="card-title">🗓️ 今日进度</div><span style="font-size:10px;color:var(--muted)">${d.getMonth()+1}月${d.getDate()}日 星期${wd[d.getDay()]}</span></div><div class="progress-body"><div class="progress-ring" style="--p:${p}%"><div class="progress-center"><strong>${n}/${cc.length}</strong><span>今日完成</span></div></div><div class="stat-list"><div class="stat"><span>⭐ 我的积分</span><strong>${state.points}</strong></div><div class="stat"><span>🐟 我的小鱼</span><strong>${state.fish}</strong></div><div class="stat"><span>📅 本周完成</span><strong>${weekFull()}/7</strong></div></div></div></article>
<article class="card soft-amber"><div class="card-head"><div class="card-title">🐾 我的宠物 · 奶糕</div><button class="mini-action" data-go="pet">›</button></div><div class="pet-body"><div class="pet-scene"><div class="pet-bubble">${esc(state.pet.message)}</div><div class="cat">🐈</div></div><div class="pet-side"><div class="pet-status"><span>💗 心情</span><b>${state.pet.mood}%</b></div><div class="mood-bar"><i style="width:${state.pet.mood}%"></i></div><div class="pet-status"><span>🐟 小鱼</span><b>${state.fish}</b></div><div class="pet-actions">${[['feed','🥣','喂食'],['play','🧶','玩耍'],['bath','🫧','洗澡'],['treat','🧰','护理']].map(x=>`<button class="pet-action" data-q="${x[0]}"><b>${x[1]}</b>${x[2]}</button>`).join('')}</div></div></div></article>
<article class="card soft-pink"><div class="card-head"><div class="card-title">🏆 我的奖励</div><button class="text-action" data-go="rewards">去兑换 ›</button></div><div class="reward-body"><div class="points-row"><strong>${state.points}</strong> 积分</div><div class="reward-track">${fixedRewards.map((r,i)=>`<div class="reward-node" style="left:${[18,50,82][i]}%"><i>${r.emoji}</i><b>${r.points}分</b><small>${r.title}</small></div>`).join('')}</div><div class="lock-note">🔒 本周满额 3 / 5 / 7 天解锁对应奖励</div></div></article>
<article class="card tasks-card"><div class="tasks-toolbar"><h2>✅ 今日任务 <small>完成一项 +2分 +1🐟</small></h2><div class="pager"><button data-prev>‹</button><span class="page-pill">${tp+1}/${pages}</span><button data-next>›</button></div></div><div class="task-slider" id="slider"><div class="task-row">${slice.map(taskCard).join('')}</div></div></article>
<article class="card soft-blue week-card"><div class="card-head"><div class="card-title">🗓️ 本周打卡</div><button class="mini-action" data-go="calendar">›</button></div><div class="week-body">${weekMini()}</div></article></div>`;
bindGo();page.querySelectorAll('[data-check]').forEach(b=>b.onclick=()=>complete(b.dataset.check));page.querySelector('[data-prev]').onclick=()=>{pauseUntil=Date.now()+15000;tp=(tp-1+pages)%pages;home()};page.querySelector('[data-next]').onclick=()=>{pauseUntil=Date.now()+15000;tp=(tp+1)%pages;home()};page.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{state.pet.message='先去商城给奶糕准备对应用品吧～';save();toast(state.pet.message);home()});
const s=$('#slider');if(s&&pages>1){let x=0;s.ontouchstart=e=>{x=e.touches[0].clientX;pauseUntil=Date.now()+15000};s.ontouchend=e=>{let dx=e.changedTouches[0].clientX-x;if(Math.abs(dx)>40){tp=(tp+(dx<0?1:-1)+pages)%pages;home()}}}
clearInterval(timer);if(pages>1)timer=setInterval(()=>{if(Date.now()>pauseUntil&&cur==='home'){tp=(tp+1)%pages;home()}},10000)
}
function taskCard(t){const d=done(t.id);return `<div class="task-card ${d?'done':''}"><div class="task-icon" style="--ib:${meta[t.subject]?.[2]||'#f4f1ee'}">${t.icon}</div><div><div class="task-name">${esc(t.name)}</div><div class="task-status">${d?'今天已完成 ✓':'今日未完成'}</div></div><button class="check-btn ${d?'done':''}" data-check="${t.id}" ${d?'disabled':''}>${d?'已完成 ✓':'完成打卡 +2分'}</button></div>`}
function complete(id){const r=rec(key());if(r.completed.includes(id))return;r.completed.push(id);state.points+=2;state.fish++;state.pet.mood=Math.min(100,state.pet.mood+2);state.pet.message='收到一条小鱼！你今天又前进了一点点。';save();pauseUntil=Date.now()+15000;toast('完成啦！+2分 · 🐟 +1');home()}
function weekMini(){let now=new Date();now.setHours(0,0,0,0);return `<div class="week-days">${weekDates().map(d=>{const f=d>now,ok=!f&&full(d),today=key(d)===key(now);return `<div><div class="weekday">${['一','二','三','四','五','六','日'][(d.getDay()+6)%7]}</div><div class="day-dot ${f?'future':ok?'done':'missed'} ${today?'today':''}">${ok?'✓':f?'':'·'}</div></div>`}).join('')}</div><div class="legend">绿色已打卡 · 粉色未打卡 · 灰色未到时间</div>`}
function subject(s){const m=meta[s],arr=state.tasks.filter(t=>t.subject===s);page.innerHTML=`<div class="page-panel"><div class="section-hero"><div><h1>${m[1]} ${m[0]}</h1><p>这里只设置打卡任务，不放学习内容。任务名称、日期与满额规则都可以调整。</p></div><button class="primary-btn" data-add>＋ 新增任务</button></div><div class="grid-cards">${arr.map(t=>`<div class="feature-card"><div class="feature-top"><div class="feature-icon" style="background:${m[2]}">${t.icon}</div><span class="chip">${t.core?'计入满额':'加分任务'}</span></div><h3>${esc(t.name)}</h3><p>${daysText(t.days)}</p><div class="card-actions"><button class="secondary-btn" data-edit="${t.id}">编辑</button>${t.builtin?'':`<button class="danger-btn" data-del="${t.id}">删除</button>`}</div></div>`).join('')}<button class="feature-card add-card" data-add>＋ 新增${m[0]}任务</button></div></div>`;page.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>taskModal(s));page.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>taskModal(s,b.dataset.edit));page.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>{state.tasks=state.tasks.filter(t=>t.id!==b.dataset.del);save();subject(s)})}
function daysText(a){return a.length===7?'每天':'每周'+a.slice().sort((x,y)=>((x+6)%7)-((y+6)%7)).map(d=>'星期'+wd[d]).join('、')}
function taskModal(s,id){const ex=id&&state.tasks.find(t=>t.id===id),t=ex||{name:'',icon:meta[s][1],days:[0,1,2,3,4,5,6],core:1};modal(`<h2>${ex?'编辑':'新增'}${meta[s][0]}任务</h2><div class="field"><label>任务名称</label><input id="tn" value="${esc(t.name)}"></div><div class="field"><label>图标</label><input id="ti" value="${esc(t.icon)}"></div><div class="field"><label>出现日期</label><div class="days-check">${[1,2,3,4,5,6,0].map(d=>`<label><input type="checkbox" name="day" value="${d}" ${t.days.includes(d)?'checked':''}>周${wd[d]}</label>`).join('')}</div></div><div class="field"><label><input type="checkbox" id="tc" ${t.core?'checked':''}> 计入当天满额</label></div><div class="modal-actions"><button class="secondary-btn" data-close>取消</button><button class="primary-btn" id="saveTask">保存</button></div>`);$('#saveTask').onclick=()=>{const name=$('#tn').value.trim(),icon=$('#ti').value.trim()||meta[s][1],days=[...document.querySelectorAll('input[name="day"]:checked')].map(x=>+x.value);if(!name||!days.length)return toast('请填写任务名并至少选择一天');if(ex)Object.assign(ex,{name,icon,days,core:$('#tc').checked});else state.tasks.push({id:'custom-'+Date.now(),subject:s,name,icon,days,core:$('#tc').checked,builtin:0});save();closeModal();subject(s)}}
function renderShop(){const c=state.shopCat||'食物',items=shop.filter(i=>i.cat===c);page.innerHTML=`<div class="page-panel"><div class="section-hero"><div><h1>🛒 小鱼商城</h1><p>学习赚小鱼，兑换奶糕用品。当前 🐟 <b>${state.fish}</b></p></div></div><div class="shop-cats">${['食物','玩具','洗漱','医疗'].map(x=>`<button class="cat-tab ${x===c?'active':''}" data-cat="${x}">${x}</button>`).join('')}</div><div class="shop-grid">${items.map(i=>`<div class="shop-item"><div class="shop-icon">${i.emoji}</div><h3>${i.name}</h3><p>与奶糕互动时使用</p><button data-buy="${i.id}">🐟 ${i.cost} · 兑换</button></div>`).join('')}</div></div>`;page.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{state.shopCat=b.dataset.cat;save();renderShop()});page.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{const i=shop.find(x=>x.id===b.dataset.buy);if(state.fish<i.cost)return toast('小鱼还不够');state.fish-=i.cost;state.inventory[i.id]=(state.inventory[i.id]||0)+1;save();toast(i.name+' 已放进宠物用品');renderShop()})}
function renderPet(){const own=shop.filter(i=>(state.inventory[i.id]||0)>0);page.innerHTML=`<div class="page-panel"><div class="section-hero"><div><h1>🐾 奶糕的小屋</h1><p>互动是轻量反馈，不增加新的必须完成任务。</p></div><b>🐟 ${state.fish}</b></div><div class="pet-large"><div class="pet-stage"><div class="pet-message">${esc(state.pet.message)}</div><div class="cat">🐈</div></div><div class="card" style="padding:12px"><h3>奶糕的状态</h3><div class="pet-status"><span>💗 心情</span><b>${state.pet.mood}%</b></div><div class="mood-bar"><i style="width:${state.pet.mood}%"></i></div><h3>我的宠物用品</h3><div class="pet-inventory">${own.length?own.map(i=>`<div class="inv-card"><b>${i.emoji} ${i.name}</b><br>×${state.inventory[i.id]}<br><button class="secondary-btn" data-use="${i.id}">使用</button></div>`).join(''):'还没有用品，去商城看看吧。'}</div></div></div></div>`;page.querySelectorAll('[data-use]').forEach(b=>b.onclick=()=>{const i=shop.find(x=>x.id===b.dataset.use);if(!i||!state.inventory[i.id])return;state.inventory[i.id]--;state.pet.mood=Math.min(100,state.pet.mood+5);state.pet.message={feed:'奶糕低头吃起来，尾巴开心地晃了晃。',play:'奶糕追着玩具扑来扑去！',groom:'奶糕乖乖坐好享受护理。',bath:'花洒打开，泡泡冒出来啦！',treat:'奶糕接受了模拟护理，安静休息。',rest:'奶糕舒服地蜷起来休息。'}[i.action];save();toast('奶糕有回应啦');renderPet()})}
function renderRewards(){const f=weekFull(),all=[...fixedRewards,...state.customRewards];page.innerHTML=`<div class="page-panel"><div class="section-hero"><div><h1>🎁 奖励中心</h1><p>当前 ${state.points}分 · 本周满额 ${f}/7天</p></div><button class="primary-btn" id="addReward">＋ 自定义奖励</button></div><div class="rewards-grid">${all.map(r=>{let u=f>=(r.days||0),e=state.points>=r.points;return `<div class="reward-card ${u?'':'locked'}"><div class="reward-emoji">${r.emoji||'⭐'}</div><h3>${esc(r.title)}</h3><p>${r.points}积分${r.days?' · 满额'+r.days+'天解锁':' · 自定义'}</p><button class="primary-btn" data-red="${r.id}" ${(!u||!e)?'disabled':''}>${!u?'未解锁':!e?'积分不足':'兑换'}</button></div>`}).join('')}</div></div>`;$('#addReward').onclick=()=>modal('<h2>新增自定义奖励</h2><div class="field"><label>奖励名称</label><input id="rn"></div><div class="field"><label>所需积分</label><input id="rp" type="number" value="100"></div><div class="field"><label>图标</label><input id="re" value="⭐"></div><div class="modal-actions"><button class="secondary-btn" data-close>取消</button><button class="primary-btn" id="rs">保存</button></div>');setTimeout(()=>{if($('#rs'))$('#rs').onclick=()=>{let title=$('#rn').value.trim(),points=+$('#rp').value,emoji=$('#re').value||'⭐';if(!title||points<2)return toast('请填写有效内容');state.customRewards.push({id:'r-'+Date.now(),title,points,emoji,days:0});save();closeModal();renderRewards()}},0);page.querySelectorAll('[data-red]').forEach(b=>b.onclick=()=>{const r=all.find(x=>x.id===b.dataset.red);if(!r||state.points<r.points||f<(r.days||0))return;state.points-=r.points;state.rewardLog.push({title:r.title,date:key(),points:r.points});save();toast('已兑换：'+r.title);renderRewards()})}
function renderCalendar(){const n=new Date(),y=n.getFullYear(),m=n.getMonth(),first=new Date(y,m,1),last=new Date(y,m+1,0),cells=[];for(let i=0;i<(first.getDay()+6)%7;i++)cells.push('');for(let d=1;d<=last.getDate();d++)cells.push(d);while(cells.length%7)cells.push('');let mf=0;for(let d=1;d<=n.getDate();d++)if(full(new Date(y,m,d)))mf++;page.innerHTML=`<div class="page-panel"><div class="section-hero"><div><h1>🗓️ 学习日历</h1><p>绿色已打卡，粉色未打卡，灰色未到时间。</p></div><b>${y}.${String(m+1).padStart(2,'0')}</b></div><div class="calendar-wrap"><div class="calendar-card"><div class="calendar-head"><h2>${y}年${m+1}月</h2></div><div class="calendar-grid">${['一','二','三','四','五','六','日'].map(x=>`<div class="cal-week">${x}</div>`).join('')}${cells.map(d=>{if(!d)return'<div></div>';let dt=new Date(y,m,d),today=new Date();today.setHours(0,0,0,0);dt.setHours(0,0,0,0);let c=dt>today?'future':full(dt)?'done':'missed';return `<div class="cal-day ${c} ${d===n.getDate()?'today':''}">${d}</div>`}).join('')}</div></div><div class="stats-card"><h2>本月统计</h2><div class="stat-big">${mf}天</div><p>已完成满额打卡</p><button class="secondary-btn" id="export">导出备份</button><button class="secondary-btn" id="import">导入备份</button></div></div></div>`;$('#export').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='喵喵打卡备份-'+key()+'.json';a.click()};$('#import').onclick=()=>$('#importInput').click()}
$('#importInput').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());state={...init(),...d};save();toast('备份已恢复');render()}catch{toast('备份文件无法读取')}e.target.value=''};
function bindGo(){page.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go))}
function modal(h){$('#modalRoot').innerHTML='<div class="modal-backdrop"><div class="modal">'+h+'</div></div>';document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal)}
function closeModal(){$('#modalRoot').innerHTML=''}
renderNav();home();if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
})();